In [1]:
%%html

iris(붓꽃) 데이터 셋은 꽃잎과 꽃받침의 길이와 너비를 이용하여 3개의 종으로 분류(classification)하는 것임

iris(붓꽃) 데이터 셋은 꽃잎과 꽃받침의 길이와 너비를 이용하여 3개의 종으로 분류(classification)하는 것임

In [3]:
import numpy as np
from sklearn import datasets
iris = datasets.load_iris()
iris_X = iris.data
iris_y = iris.target
np.unique(iris_y)

array([0, 1, 2])

In [4]:
%%html
<img src="files/sphx_glr_plot_iris_dataset_001.png">

<img src="files/sphx_glr_plot_iris_dataset_001.png">

In [5]:
%%html
classifier 를 하는 가장 간단한 방법은 kNN 임

classifier 를 하는 가장 간단한 방법은 kNN 임

In [6]:
# split iris data in training data and test data
# A random permutation, to split the data randomly
np.random.seed(0)
indices = np.random.permutation(len(iris_X))

iris_X_train = iris_X[indices[:-10]]
iris_y_train = iris_y[indices[:-10]]
iris_X_test = iris_X[indices[-10:]]
iris_y_test = iris_y[indices[-10:]]

# create and fit a kNN model
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(iris_X_train, iris_y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [7]:
knn.predict(iris_X_test)

array([1, 2, 1, 0, 0, 0, 2, 1, 2, 0])

In [8]:
iris_y_test

array([1, 1, 1, 0, 0, 0, 2, 1, 2, 0])

In [9]:
%%html
<p>For an estimator to be effective, you need the distance between neighboring points to be less than some value d, which depends on the problem. In one dimension, this requires on average n ~ 1/d points. In the context of the above k-NN example, if the data is described by just one feature with values ranging from 0 to 1 and with n training observations, then new data will be no further away than 1/n. Therefore, the nearest neighbor decision rule will be efficient as soon as 1/n is small compared to the scale of between-class feature variations</p>
</br>
<p>If the number of features is p, you now require n ~ 1/d^p points. Let’s say that we require 10 points in one dimension: now 10^p points are required in p dimensions to pave the [0, 1] space. As p becomes large, the number of training points required for a good estimator grows exponentially.</p>
For example, if each point is just a single number (8 bytes), then an effective k-NN estimator in a paltry p~20 dimensions would require more training data than the current estimated size of the entire internet (±1000 Exabytes or so).
</br>
<p>This is called the curse of dimensionality and is a core problem that machine learning addresses.</p>

<p>For an estimator to be effective, you need the distance between neighboring points to be less than some value d, which depends on the problem. In one dimension, this requires on average n ~ 1/d points. In the context of the above k-NN example, if the data is described by just one feature with values ranging from 0 to 1 and with n training observations, then new data will be no further away than 1/n. Therefore, the nearest neighbor decision rule will be efficient as soon as 1/n is small compared to the scale of between-class feature variations</p>
</br>
<p>If the number of features is p, you now require n ~ 1/d^p points. Let’s say that we require 10 points in one dimension: now 10^p points are required in p dimensions to pave the [0, 1] space. As p becomes large, the number of training points required for a good estimator grows exponentially.</p>
For example, if each point is just a single number (8 bytes), then an effective k-NN estimator in a paltry p~20 dimensions would require more training data than the current estimated size of the entire internet (±1000 Exabytes or so).
</br>
<p>This is called the curse of dimensionality and is a core problem that machine learning addresses.</p>